apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:1.5-alpine
        env:
        - name: POSTGRES_USER
          value: <username>
        - name: POSTGRES_PASSWORD
          value: <password>