apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  Type: NodePort
  selector:
    matchLabels:
      app: result
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30051