apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  matchLabels:
    app: worker
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: docker/example-voting-app-worker